### ISSUE TITLE
Update product bundle identifier

### ISSUE THREAD

**Issue by felixvisee** [rheinfabrik/Dobby#31]
After the recent project transfer from Rheinfabrik to trivago ([see this](https://github.com/trivago/Dobby/commit/da55aafc1a9fd60471e04546e44ee34dc5a95533)), I'm wondering whether we should also update the [product bundle identifier](https://github.com/trivago/Dobby/blob/f5a7814404781973459d18744efc3a0442231124/Dobby.xcodeproj/project.pbxproj#L555) and the [organization name](https://github.com/trivago/Dobby/blob/f5a7814404781973459d18744efc3a0442231124/Dobby.xcodeproj/project.pbxproj#L419) (probably)? Any objections from your side, @tibr?

**Comment by tibr** [comment]
You're right, thanks for creating the issue 👍 
It should be changed to `com.trivago.dobby` instead.

**Comment by felixvisee** [comment]
What about the author's email in the pod spec (currently `hi@rheinfabrik.de`) and the Social Media URL (currently `https://twitter.com/rheinfabrik`)?

**Comment by tibr** [comment]
@felixjendrusch Social Media URL would probably best set to https://twitter.com/trivago_tech. No idea for the email, is that mandatory? If it is, we can leave it at hi@rheinfabrik.de for now. @hffmnn maybe you want to setup an email address for cases like this?
