### ISSUE TITLE
Build warnings in 0.7.0

### ISSUE THREAD

**Issue by mdarnall** [rheinfabrik/Dobby#41]
Hi, 

Related to my response in #34, I noticed that building Dobby @0.7.0 results in this warning (from Xcode or via Carthage integration):

```
ld: warning: linking against a dylib which is not safe for use in application extensions: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/Frameworks/XCTest.framework/XCTest.tbd
ld: warning: linking against a dylib which is not safe for use in application extensions: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator/libswiftXCTest.dylib
```

Looking into this further, Dobby sets `APPLICATION_EXTENSION_API_ONLY = YES` via the `Configuration/Base/Targets/Frameworks.xcconfig` configuration file. 

```
// Disallows use of APIs that are not available
// to app extensions and linking to frameworks
// that have not been built with this setting enabled.
APPLICATION_EXTENSION_API_ONLY = YES
```

While this probably makes sense for most frameworks, does it make sense for Dobby? The warning seems to stem from the fact that Dobby links/requires `XCTest` which itself doesn't seem to have been built with this setting enabled. 

I've tested that overriding that setting for the `Dobby-iOS` target removes the warnings. I kind of think that Dobby as a unit-test framework that links against XCTest shouldn't disallow the use of APIs that are not available to app extensions. Thoughts? 

I can open a PR with this change if you agree: https://github.com/trivago/Dobby/compare/master...mdarnall:dont-require-app-extension-apis

**Comment by felixvisee** [comment]
Thanks for looking into this, @mdarnall. After checking the [origin](https://github.com/jspahrsummers/xcconfigs/pull/36) of this setting and comparing with Quick, I do agree we should change this. Please open a pull request!
